apiVersion: apps/v1
kind: Deployment
metadata:
  name: yurecollect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yurecollect
  template:
    metadata:
      labels:
        app: yurecollect
    spec:
      containers:
        - name: yurecollect
          image: ghcr.io/yude/yurecollect:sha-18483c8
          args:
            - "wss://unstable.kusaremkn.com/yure/"
          resources:
            limits:
              memory: "1560Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
