apiVersion: v1
kind: ConfigMap
metadata:
  name: annict-activity-to-mastodon-config
data:
  config.toml: |
    [credentials.annict]
    key = ""
    username = "yude"

    [credentials.misskey]
    domain = "https://misskey.y2e.org"
    access_token = ""
